# By: XIAYM-gh, Original author: FBIKdot
# Respecting the Aseprite EULA, this "private" action will upload its artifacts to the drafts.

name: P - Aseprite - Windows x64

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      useMainCommit:
        description: "Use the latest commit (Default true)"
        type: boolean
        default: true

      tagName:
        description: "Or specific the tag name (e.g. v1.3.2)"
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check user input
        shell: bash
        run: |
          if [[ "${{ github.event.inputs.useMainCommit }}" == "false" ]] && [[ "${{ github.event.inputs.tagName }}" == "" ]]; then
            echo ERROR: No Tag Name Specificed.
            exit 1
          fi

      - name: Clone Aseprite
        shell: bash
        run: |
          ARGS=""
          if [[ "${{ github.event.inputs.useMainCommit }}" == "false" ]]; then
            ARGS="--branch ${{ github.event.inputs.tagName }}"
          fi

          git clone "https://github.com/aseprite/aseprite" repo $ARGS --depth 1
          cd repo
          git submodule update --init --recursive

      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Get skia & Generate Makefile
        shell: bash
        run: |
          cd repo

          curl -L -o skia.zip https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
          7z x skia.zip -oskia
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_UI=on \
            -DENABLE_CCACHE=off \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=./skia \
            -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
            -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib

      - name: Compile
        shell: bash
        run: |
          cd repo/build && ninja

      - name: Get "libcrypto-1_1-x64.dll"
        shell: bash
        run: |
          curl -L -o repo/build/bin/libcrypto-1_1-x64.dll https://github.com/feenkcom/libopenssl/releases/download/v0.5.0/crypto-x86_64-pc-windows-msvc.dll

      - name: Package
        shell: bash
        run: |
          cd repo/build/bin/
          7z a -tzip aseprite.zip data aseprite.exe libcrypto-1_1-x64.dll
          cp aseprite.zip D:/a/

      - name: Draft Release & Upload
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 'ase_${{ github.run_id }}'
          name: 'Aseprite Build -  ${{ github.run_id }}'
          body: 'Nothing but a aseprite release, DO NOT PUBLISH IT'
          draft: true
          prerelease: false
          files: |
            D:/a/aseprite.zip
