# By: XIAYM-gh, Original author: FBIKdot
# Respecting the Aseprite EULA, this "private" action will upload its artifacts to the drafts.

name: P - Aseprite - Windows x64

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      branchToUse:
        description: 'Specific the branch to use (e.g. v1.3.2)'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Aseprite
        uses: actions/checkout@v4
        with:
          repository: 'aseprite/aseprite'
          ref: '${{ inputs.branchToUse }}'
          submodules: 'recursive'

      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Get skia & Generate Makefile
        shell: bash
        run: |
          curl -L -o skia.zip https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
          7z x skia.zip -oskia
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_UI=on \
            -DENABLE_CCACHE=off \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=./skia \
            -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
            -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib

      - name: Compile
        shell: bash
        run: cd build && ninja

      - name: Get "libcrypto-1_1-x64.dll"
        shell: bash
        run: |
          curl -L -o build/bin/libcrypto-1_1-x64.dll https://github.com/feenkcom/libopenssl/releases/download/v0.5.0/crypto-x86_64-pc-windows-msvc.dll

      - name: Package
        shell: bash
        run: |
          cd build/bin/
          7z a -t7z -mx=9 aseprite.7z data aseprite.exe libcrypto-1_1-x64.dll
          cp aseprite.7z D:/a/

      - name: Draft Release & Upload
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 'ase_${{ github.run_id }}'
          name: 'Aseprite Build -  ${{ github.run_id }}'
          body: 'Nothing but a aseprite release, DO NOT PUBLISH IT'
          draft: true
          prerelease: false
          files: |
            D:/a/aseprite.7z
