# By: XIAYM-gh

name: Build Project with Maven

on:
  workflow_dispatch:
    inputs:
      repoAddress:
        description: "仓库地址 (e.g. XIAYM-gh/Simple-Mirai-Bot)"
        required: true

      javaVersion:
        description: "Java 版本 (默认为 17)"

        type: choice
        options:
          - "8"
          - "11"
          - "17"
        default: "17"

        required: true

      buildArgument:
        description: "构建时所用的命令 (e.g. package)"
        required: true
        default: "package"

      uploadJars:
        description: "是否在构建后上传 target 文件夹中所有的 Jar 文件"
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up maven env
      - name: Set up env
        uses: actions/setup-java@v3
        with:
          java-version: "${{ inputs.javaVersion }}"
          distribution: temurin

      - name: Clone full repository
        run: |
          git clone "https://github.com/${{ inputs.repoAddress }}" repository
      
      - name: Build now
        run: |
          cd repository
          mvn -B --file pom.xml ${{ inputs.buildArgument }}

      - name: Upload target directory
        uses: actions/upload-artifact@v3
        with:
          name: Target Directory
          path: repository/target

      - name: Upload target jar files
        if: ${{ inputs.uploadJars }}
        uses: actions/upload-artifact@v3
        with:
          name: Target Jars
          path: repository/target/*.jar