# By: XIAYM-gh

name: Build Project with Gradle

on:
  workflow_dispatch:
    inputs:
      repoAddress:
        description: "仓库地址 (e.g. NLR-DevTeam/GrassPictures)"
        required: true

      javaVersion:
        description: "Java 版本 (默认为 17)"

        type: choice
        options:
          - "8"
          - "11"
          - "17"
        default: "17"

        required: true

      buildArgument:
        description: "构建时所用的命令 (e.g. build)"
        required: true
        default: "build"

      uploadJars:
        description: "是否在构建后上传 build 文件夹中的 lib 文件夹"
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up maven env
      - name: Set up env
        uses: actions/setup-java@v3
        with:
          java-version: "${{ inputs.javaVersion }}"
          distribution: temurin

      - name: Clone full repository
        run: |
          git clone "https://github.com/${{ inputs.repoAddress }}" repository
      
      - name: Build now
        run: |
          cd repository
          chmod +x gradlew
          ./gradlew ${{ inputs.buildArgument }}

      - name: Upload build directory
        uses: actions/upload-artifact@v3
        with:
          name: Build Directory
          path: repository/build/

      - name: Upload build/libs files
        if: ${{ inputs.uploadJars }}
        uses: actions/upload-artifact@v3
        with:
          name: Build/Libs
          path: repository/build/libs/