# By: XIAYM-gh

name: Build Project with Maven

on:
  workflow_dispatch:
    inputs:
      repoAddress:
        description: 'Repo Identifier (e.g. XIAYM-gh/Simple-Mirai-Bot)'
        required: true

      javaVersion:
        description: 'Java Ver (21 by default)'

        type: choice
        options:
          - '8'
          - '11'
          - '17'
          - '21'
        default: '21'

        required: true

      buildArgument:
        description: 'Build Command (e.g. clean package)'
        required: true
        default: 'package'

      uploadRepo:
        description: 'Upload the whole repository'
        type: boolean
        required: false

      uploadJars:
        description: 'Upload jars inside target folder'
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: '${{ inputs.repoAddress }}'

      - name: Set up git auth
        run: |
          git config --global user.name ActionsRunner
          git config --global user.email git@github.com

      - name: Set up env
        uses: actions/setup-java@v4
        with:
          java-version: '${{ inputs.javaVersion }}'
          distribution: temurin
      
      - name: Build now
        run: mvn -B --file pom.xml ${{ inputs.buildArgument }}

      - name: Upload target directory
        uses: actions/upload-artifact@v4
        with:
          name: Target Directory
          path: target/

      - name: Compress the whole repository's files
        if: ${{ inputs.uploadRepo }}
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 repository.7z *

      - name: Upload the whole repository's zipped file
        if: ${{ inputs.uploadRepo }}
        uses: actions/upload-artifact@v4
        with:
          name: Whole Repository (Unzip 2 times)
          path: repository.7z
          compression-level: 0

      - name: Upload target jar files
        if: ${{ inputs.uploadJars }}
        uses: actions/upload-artifact@v3
        with:
          name: Target Jars
          path: target/*.jar