# By: XIAYM-gh

name: Build Project with Maven

on:
  workflow_dispatch:
    inputs:
      repoAddress:
        description: "Repo Identifier (e.g. XIAYM-gh/Simple-Mirai-Bot)"
        required: true

      javaVersion:
        description: "Java Ver (21 by default)"

        type: choice
        options:
          - "8"
          - "11"
          - "17"
          - "21"
        default: "21"

        required: true

      buildArgument:
        description: "Build Command (e.g. clean package)"
        required: true
        default: "package"

      uploadRepo:
        description: "Upload the whole repository"
        type: boolean
        required: false

      uploadJars:
        description: "Upload jars inside target folder"
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up maven env
      - name: Set up env
        uses: actions/setup-java@v3
        with:
          java-version: "${{ inputs.javaVersion }}"
          distribution: temurin

      - name: Clone full repository
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "Actions-Runner"
          git clone "https://github.com/${{ inputs.repoAddress }}" repository
      
      - name: Build now
        run: |
          cd repository
          mvn -B --file pom.xml ${{ inputs.buildArgument }}

      - name: Upload target directory
        uses: actions/upload-artifact@v3
        with:
          name: Target Directory
          path: repository/target/

      - name: Compress the whole repository's files
        if: ${{ inputs.uploadRepo }}
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 repository.7z ./repository/

      - name: Upload the whole repository's zipped file
        if: ${{ inputs.uploadRepo }}
        uses: actions/upload-artifact@v3
        with:
          name: Whole Repository (Unzip TWO times)
          path: repository.7z

      - name: Upload target jar files
        if: ${{ inputs.uploadJars }}
        uses: actions/upload-artifact@v3
        with:
          name: Target Jars
          path: repository/target/*.jar