# By: XIAYM-gh

name: Build Project with Gradle

on:
  workflow_dispatch:
    inputs:
      repoAddress:
        description: 'Repo Identifier (e.g. NLR-DevTeam/GrassPictures)'
        required: true

      javaVersion:
        description: 'Java Ver (21 by default)'

        type: choice
        options:
          - '8'
          - '11'
          - '17'
          - '21'
        default: '21'

        required: true

      buildArgument:
        description: 'Build Command (e.g. build)'
        required: true
        default: 'build'

      uploadRepo:
        description: 'Upload the whole repository'
        type: boolean
        required: false

      uploadLibs:
        description: 'Upload the build/libs folder'
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: '${{ inputs.repoAddress }}'

      - name: Set up env
        uses: actions/setup-java@v4
        with:
          java-version: '${{ inputs.javaVersion }}'
          distribution: temurin

      - name: Build now
        run: |
          chmod +x gradlew
          ./gradlew ${{ inputs.buildArgument }}

      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: Build Directory
          path: build/

      - name: Compress the whole repository's files
        if: ${{ inputs.uploadRepo }}
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 repository.7z *

      - name: Upload the whole repository's zipped file
        if: ${{ inputs.uploadRepo }}
        uses: actions/upload-artifact@v4
        with:
          name: Whole Repository (Unzip 2 times)
          path: repository.7z
          compression-level: 0

      - name: Upload build/libs files
        if: ${{ inputs.uploadLibs }}
        uses: actions/upload-artifact@v4
        with:
          name: Build/Libs
          path: build/libs/
