# By: XIAYM-gh

name: Iris Plugin - Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Iris
        uses: actions/checkout@v4
        with:
          repository: 'VolmitSoftware/Iris'

      - name: Set up env
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build now
        run: |
          chmod +x gradlew
          ./gradlew setup
          ./gradlew iris

      - name: Compress files
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 repository.7z ./repository/build/*.jar

      - name: Upload the 7z file
        uses: actions/upload-artifact@v4
        with:
          name: Iris Jar (Unzip 2 times)
          path: repository.7z
          compression-level: 0
